# Generated by Django 6.0 on 2026-03-01 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0022_bon_livraison'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unsigned_xml', models.BinaryField()),
                ('signature_xml', models.BinaryField(null=True)),
                ('signed_xml', models.BinaryField(null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('signed', 'Signed'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.invoice')),
            ],
        ),
    ]
