# Generated by Django 6.0 on 2026-03-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='govinvoice',
            name='ngsign_invoice_uuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='govinvoice',
            name='ngsign_status',
            field=models.CharField(blank=True, choices=[('CREATED', 'CREATED'), ('SIGNED', 'SIGNED'), ('TTN_ACCEPTED', 'TTN_ACCEPTED'), ('TTN_REJECTED', 'TTN_REJECTED'), ('CANCELLED', 'CANCELLED'), ('ERROR', 'ERROR')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='govinvoice',
            name='ngsign_transaction_uuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
