# Generated by Django 6.0 on 2026-03-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0002_add_ngsign_fields_to_govinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govinvoice',
            name='ngsign_status',
            field=models.CharField(blank=True, choices=[('CREATED', 'CREATED'), ('CONFIGURED', 'CONFIGURED'), ('SIGNED', 'SIGNED'), ('CANCELLED', 'CANCELLED'), ('TTN_TRANSFERED', 'TTN_TRANSFERED'), ('TTN_NOTTRANSFERED', 'TTN_NOTTRANSFERED'), ('TTN_REJECTED', 'TTN_REJECTED'), ('TTN_SIGNED', 'TTN_SIGNED'), ('MIXED', 'MIXED'), ('ERROR', 'ERROR')], max_length=50, null=True),
        ),
    ]
