# Generated by Django 6.0 on 2026-03-18 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0003_update_ngsign_status_choices'),
        ('sales', '0023_devis_invoiceservice_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='govinvoice',
            name='credit_note',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.creditnote'),
        ),
        migrations.AlterField(
            model_name='govinvoice',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.invoice'),
        ),
    ]
