# Generated by Django 6.0 on 2026-03-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0004_govinvoice_credit_note_alter_govinvoice_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='govinvoice',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='govinvoice',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='govinvoice',
            name='ngsign_status',
            field=models.CharField(blank=True, choices=[('SUBMITTING', 'SUBMITTING'), ('CREATED', 'CREATED'), ('CONFIGURED', 'CONFIGURED'), ('SIGNED', 'SIGNED'), ('CANCELLED', 'CANCELLED'), ('TTN_TRANSFERED', 'TTN_TRANSFERED'), ('TTN_NOTTRANSFERED', 'TTN_NOTTRANSFERED'), ('TTN_REJECTED', 'TTN_REJECTED'), ('TTN_SIGNED', 'TTN_SIGNED'), ('MIXED', 'MIXED'), ('ERROR', 'ERROR')], max_length=50, null=True),
        ),
    ]
