# Generated by Django 6.0 on 2026-05-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0005_govinvoice_notes_govinvoice_submitted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='govinvoice',
            name='elfatoora_generated_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='govinvoice',
            name='elfatoora_last_ack_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='govinvoice',
            name='elfatoora_last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='govinvoice',
            name='elfatoora_status',
            field=models.CharField(blank=True, choices=[('SUBMITTED', 'SUBMITTED'), ('ACKNOWLEDGED', 'ACKNOWLEDGED'), ('REJECTED', 'REJECTED'), ('ERROR', 'ERROR')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='govinvoice',
            name='elfatoora_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
