# Generated by Django 5.2.8 on 2026-01-12 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0003_invoice_is_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ACQUISITIONS', '1. Acquisitions des marchandises, matériel, équipements et services'), ('LOYERS', '2. Loyers'), ('ACTIVITES_NC', '3. Rémunération des activités non commerciales'), ('CESSIONS', '4. Cessions de fonds de commerce et immeubles'), ('DIVIDENDES', '5. Dividendes'), ('CAPITAUX', '6. Revenus des capitaux mobiliers'), ('JEUX', '7. Jeux de pari et loterie'), ('JETONS', '8. Jetons de présence et tantièmes')], max_length=20, verbose_name='Catégorie')),
                ('subcategory', models.CharField(choices=[('ACQ_PM_IS', "Acquisitions auprès de personnes morales soumises à l'IS (règle générale) - 1%"), ('ACQ_COMMISSION_PM', 'Commission des distributeurs agréés (PM) - 2%'), ('ACQ_1000_2_3', 'Acquisitions ≥ 1.000 D TTC (PP 2/3 ou PM IS 10%) - 0.5%'), ('ACQ_1000_OTHER', 'Acquisitions ≥ 1.000 D TTC (IS autre que 15% et 10%) - 1%'), ('ACQ_1000_15', 'Acquisitions ≥ 1.000 D TTC (IS 15%) - 1.5%'), ('ACQ_COMMISSION_PP', 'Commission des distributeurs agréés (PP) - 5%'), ('LOYER_HOTEL', "Loyers d'hôtels - 10%"), ('LOYER_RESIDENT', 'Loyers résidents établis - 10%'), ('BNC_REEL', 'Honoraires BNC régime réel - 10%'), ('REMUN_PERFORMANCE', 'Rémunérations performance - 10%'), ('REMUN_ARTISTES', 'Rémunérations artistes et créateurs - 5%'), ('BNC_FORFAIT', "Honoraires BNC forfait d'assiette - 15%"), ('CESSION_FONDS', 'Cession de fonds de commerce - 5%'), ('CESSION_IMMEUBLE', "Cession d'immeubles - 2.5%"), ('DIVIDENDE_PP', 'Dividendes PP résidentes - 10%'), ('CAPITAUX_MOB', 'Revenus capitaux mobiliers - 20%'), ('JEUX_PARI', 'Jeux de pari et loterie - 25%'), ('JETONS_PRESENCE', 'Jetons de présence et tantièmes - 20%')], max_length=30, unique=True, verbose_name='Type de retenue')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taux (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Retenue à la source',
                'verbose_name_plural': 'Retenues à la source',
                'ordering': ['category', 'rate'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceRetenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_amount', models.DecimalField(decimal_places=3, help_text='Montant sur lequel la retenue est calculée', max_digits=10, verbose_name='Montant de base (D)')),
                ('retenu_rate', models.DecimalField(decimal_places=2, help_text='Taux au moment de la création', max_digits=5, verbose_name='Taux appliqué (%)')),
                ('retenu_amount', models.DecimalField(decimal_places=3, help_text='Calculé automatiquement: base_amount × (taux / 100)', max_digits=10, verbose_name='Montant retenu (D)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retenues', to='sales.invoice')),
                ('retenu_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.retenu', verbose_name='Type de retenue')),
            ],
            options={
                'verbose_name': 'Retenue sur facture',
                'verbose_name_plural': 'Retenues sur factures',
                'ordering': ['-created_at'],
            },
        ),
    ]
