# Generated by Django 5.2.8 on 2026-01-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceretenu',
            name='notes',
        ),
        migrations.AddField(
            model_name='invoiceretenu',
            name='depo_date',
            field=models.PositiveIntegerField(default=2026),
        ),
    ]
