# Generated by Django 6.0 on 2026-02-18 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_invoiceretenu_notes_invoiceretenu_depo_date'),
        ('sales', '0014_purchase_suppliertransaction_supply_purchaseline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRetenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_amount', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Montant de base (D)')),
                ('retenu_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taux appliqué (%)')),
                ('retenu_amount', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Montant retenu (D)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_retenues', to='sales.purchase')),
                ('retenu_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.retenu', verbose_name='Type de retenue')),
            ],
            options={
                'verbose_name': 'Retenue sur achat',
                'verbose_name_plural': 'Retenues sur achats',
                'ordering': ['-created_at'],
            },
        ),
    ]
