# Generated by Django 5.2.8 on 2025-11-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='dueDate',
        ),
        migrations.AddField(
            model_name='client',
            name='emailAddress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
