# Generated by Django 5.2.8 on 2025-12-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Settings', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='timbre_fiscal',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Timbre fiscal amount (overrides Settings if set)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tva',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='TVA percentage (overrides Settings if set)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='dt',
            field=models.DecimalField(blank=True, decimal_places=3, default=1.0, help_text='Default Timbre Fiscal', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='tva',
            field=models.DecimalField(blank=True, decimal_places=2, default=19.0, help_text='Default TVA percentage', max_digits=5, null=True),
        ),
    ]
