# Generated by Django 5.2.8 on 2025-12-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_settings_options_alter_invoice_timbre_fiscal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
