# Generated by Django 5.2.8 on 2025-11-27 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_invoice_duedate_client_emailaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='uniqueID',
            new_name='uniqueId',
        ),
    ]
