# Generated by Django 5.2.8 on 2026-01-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_invoice_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(blank=True, choices=[('Person Physique', 'PP'), ('Person Moral', 'PM')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='status',
            field=models.CharField(blank=True, choices=[('Person Physique', 'PP'), ('Person Moral', 'PM')], max_length=200, null=True),
        ),
    ]
