# Generated by Django 5.2.8 on 2025-11-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_rename_uniqueid_invoice_uniqueid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='product',
        ),
        migrations.AddField(
            model_name='invoice',
            name='product',
            field=models.ManyToManyField(blank=True, to='sales.product'),
        ),
    ]
