# Generated by Django 5.2.8 on 2025-11-27 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_invoice_product_invoice_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='product',
            new_name='products',
        ),
    ]
