# Generated by Django 5.2.8 on 2025-11-27 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_rename_product_invoice_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='products',
            new_name='product',
        ),
    ]
