# Generated by Django 5.2.8 on 2026-01-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='rib',
            field=models.CharField(blank=True, help_text='RIB', max_length=100, null=True),
        ),
    ]
