# Generated by Django 5.2.8 on 2026-01-20 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_settings_rib'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceservice',
            old_name='service',
            new_name='item',
        ),
        migrations.AddField(
            model_name='invoiceservice',
            name='has_fodec',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoiceservice',
            name='units_used',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='apply_fodec',
            field=models.BooleanField(default=False, help_text='Check if 1% FODEC applies'),
        ),
        migrations.AddField(
            model_name='service',
            name='item_type',
            field=models.CharField(choices=[('service', 'Service'), ('good', 'Physical Good')], default='service', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoiceservice',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='sales.invoice'),
        ),
        migrations.AlterField(
            model_name='invoiceservice',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.AlterField(
            model_name='service',
            name='billing_type',
            field=models.CharField(choices=[('flat', 'Flat Rate'), ('day', 'Per Day'), ('hour', 'Per Hour'), ('unit', 'Per Piece/Unit')], default='flat', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=20, null=True),
        ),
    ]
