# Generated by Django 5.2.8 on 2025-11-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_rename_products_invoice_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='dt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='tva',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
