# Generated by Django 5.2.8 on 2025-11-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_settings_dt_settings_tva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
