# Generated by Django 6.0 on 2026-01-23 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_rename_service_invoiceservice_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceservice',
            old_name='item',
            new_name='services',
        ),
    ]
