# Generated by Django 5.2.8 on 2025-11-29 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.settings'),
        ),
    ]
