# Generated by Django 6.0 on 2026-01-23 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_rename_item_invoiceservice_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceservice',
            old_name='services',
            new_name='invoice_services',
        ),
    ]
