# Generated by Django 5.2.8 on 2025-11-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_invoice_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='settings',
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage', max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='timbre_fiscal',
            field=models.DecimalField(decimal_places=3, default=1.0, help_text='Timbre fiscal amount (D)', max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=19.0, help_text='TVA percentage', max_digits=5),
        ),
    ]
