# Generated by Django 6.0 on 2026-01-23 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_rename_services_invoiceservice_invoice_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceservice',
            old_name='invoice_services',
            new_name='services',
        ),
        migrations.AlterField(
            model_name='invoiceservice',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_services', to='sales.invoice'),
        ),
    ]
