# Generated by Django 6.0 on 2026-01-23 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_rename_invoice_services_invoiceservice_services_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='item_type',
            new_name='service_type',
        ),
    ]
