# Generated by Django 6.0 on 2026-01-23 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_rename_item_type_service_service_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceservice',
            old_name='services',
            new_name='service',
        ),
    ]
