# Generated by Django 6.0 on 2026-02-08 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_rename_services_invoiceservice_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10)),
                ('source', models.CharField(choices=[('INVOICE_CREATED', 'Facture créée'), ('INVOICE_PAID', 'Facture payée'), ('INVOICE_DELETED', 'Facture annulée'), ('MANUAL', 'Saisie manuelle')], default='MANUAL', max_length=20)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='sales.client')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='sales.invoice')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
