# Generated by Django 6.0 on 2026-02-18 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_clienttransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('CONFIRMED', 'Confirmé'), ('RECEIVED', 'Reçu'), ('PAID', 'Payé')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tva', models.DecimalField(decimal_places=2, default=19.0, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('timbre_fiscal', models.DecimalField(decimal_places=3, default=1.0, max_digits=10)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(max_length=500, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='sales.supplier')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='SupplierTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10)),
                ('source', models.CharField(choices=[('PURCHASE_CONFIRMED', 'Achat confirmé'), ('PURCHASE_PAID', 'Achat payé'), ('PURCHASE_DELETED', 'Achat annulé'), ('MANUAL', 'Saisie manuelle')], default='MANUAL', max_length=20)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='sales.purchase')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_transactions', to='sales.supplier')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('raw_material', 'Matières premières'), ('consumable', 'Consommables'), ('packaging', 'Emballage'), ('spare_part', 'Pièces de rechange'), ('other', 'Autre')], default='raw_material', max_length=20)),
                ('unit', models.CharField(default='pièce', max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('stock_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('min_stock', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('preferred_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplies', to='sales.supplier')),
            ],
            options={
                'verbose_name': 'Fourniture',
                'verbose_name_plural': 'Fournitures',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=15)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_lines', to='sales.purchase')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.supply')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceSupplyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=3, max_digits=15)),
                ('date_used', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_usages', to='sales.invoice')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.service')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.supply')),
            ],
        ),
    ]
