# Generated by Django 6.0 on 2026-02-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_purchase_suppliertransaction_supply_purchaseline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseline',
            name='has_fodec',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supply',
            name='apply_fodec',
            field=models.BooleanField(default=False),
        ),
    ]
