# Generated by Django 6.0 on 2026-02-19 18:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_purchaseline_has_fodec_supply_apply_fodec'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Total amount paid so far (partial or full)', max_digits=15),
        ),
    ]
