# Generated by Django 6.0 on 2026-02-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_invoice_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='clientLogo',
            field=models.TextField(blank=True, help_text='Base64-encoded data URL of the company logo', null=True),
        ),
    ]
