# Generated by Django 6.0 on 2026-02-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_alter_settings_clientlogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='emailAddress',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
