# Generated by Django 6.0 on 2026-02-22 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_settings_emailaddress_settings_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttransaction',
            name='source',
            field=models.CharField(choices=[('INVOICE_CREATED', 'Facture créée'), ('INVOICE_PAID', 'Facture payée'), ('INVOICE_DELETED', 'Facture annulée'), ('AVOIR_CREATED', 'Avoir créé'), ('AVOIR_DELETED', 'Avoir annulé'), ('MANUAL', 'Saisie manuelle')], default='MANUAL', max_length=20),
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('description', models.TextField()),
                ('amount_ht', models.DecimalField(decimal_places=3, max_digits=15)),
                ('tva', models.DecimalField(decimal_places=2, default=19.0, max_digits=5)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='sales.client')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='sales.invoice')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
