# Generated by Django 6.0 on 2026-02-22 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_alter_clienttransaction_source_creditnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttransaction',
            name='credit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='sales.creditnote'),
        ),
    ]
