# Generated by Django 6.0 on 2026-03-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_clienttransaction_credit_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='default_retenu_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Taux de retenu à la source (%) appliqué automatiquement aux factures clients > 1 000 D', max_digits=5, null=True),
        ),
    ]
