# Generated by Django 6.0 on 2026-03-01 14:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_settings_default_retenu_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Envoyé'), ('DELIVERED', 'Livré')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tva', models.DecimalField(decimal_places=2, default=Decimal('19.00'), max_digits=5)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_livraison', to='sales.client')),
            ],
            options={
                'verbose_name': 'Bon de Livraison',
                'verbose_name_plural': 'Bons de Livraison',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='BonLivraisonLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('bon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.bonlivraison')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
