# Generated by Django 6.0 on 2026-03-06 19:38

import django.db.models.deletion
from django.db import migrations, models


def fix_partial_state(apps, schema_editor):
    """Idempotently ensure both the Devis table and devis_id column exist."""
    cursor = schema_editor.connection.cursor()

    # Create Devis table if missing
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS sales_devis (
            id BIGSERIAL PRIMARY KEY,
            title VARCHAR(200) NULL,
            notes TEXT NULL,
            status VARCHAR(100) NOT NULL DEFAULT 'PENDING',
            tva NUMERIC(5, 2) NULL,
            timbre_fiscal NUMERIC(10, 3) NULL,
            discount NUMERIC(10, 2) NULL DEFAULT 0.00,
            "uniqueId" VARCHAR(100) NULL,
            slug VARCHAR(500) NULL,
            date_created TIMESTAMP WITH TIME ZONE NULL,
            last_updated TIMESTAMP WITH TIME ZONE NULL,
            client_id BIGINT NULL REFERENCES sales_client(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
            converted_invoice_id BIGINT NULL REFERENCES sales_invoice(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED
        )
    """)

    # Create indexes if missing
    cursor.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE tablename='sales_devis' AND indexname='sales_devis_client_id_idx') THEN
                CREATE INDEX sales_devis_client_id_idx ON sales_devis(client_id);
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE tablename='sales_devis' AND indexname='sales_devis_slug_idx') THEN
                CREATE UNIQUE INDEX sales_devis_slug_idx ON sales_devis(slug);
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE tablename='sales_devis' AND indexname='sales_devis_converted_invoice_id_idx') THEN
                CREATE UNIQUE INDEX sales_devis_converted_invoice_id_idx ON sales_devis(converted_invoice_id);
            END IF;
        END $$;
    """)

    # Add devis_id column if missing
    cursor.execute("""
        ALTER TABLE sales_invoiceservice
        ADD COLUMN IF NOT EXISTS devis_id BIGINT NULL
    """)

    # Add FK constraint if missing
    cursor.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.table_constraints
                WHERE constraint_name = 'sales_invoiceservice_devis_id_fk'
                  AND table_name = 'sales_invoiceservice'
            ) THEN
                ALTER TABLE sales_invoiceservice
                ADD CONSTRAINT sales_invoiceservice_devis_id_fk
                FOREIGN KEY (devis_id) REFERENCES sales_devis(id)
                ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
            END IF;
        END $$;
    """)

    # Add index if missing
    cursor.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE tablename='sales_invoiceservice' AND indexname='sales_invoiceservice_devis_id_idx') THEN
                CREATE INDEX sales_invoiceservice_devis_id_idx ON sales_invoiceservice(devis_id);
            END IF;
        END $$;
    """)


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_bon_livraison'),
    ]

    operations = [
        # Make invoice FK nullable
        migrations.AlterField(
            model_name='invoiceservice',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_services', to='sales.invoice'),
        ),
        # Idempotent SQL to fix any partial state
        migrations.RunPython(fix_partial_state, migrations.RunPython.noop),
        # Register model + field in Django state (no SQL)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Devis',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(blank=True, max_length=200, null=True)),
                        ('notes', models.TextField(blank=True, null=True)),
                        ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=100)),
                        ('tva', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                        ('timbre_fiscal', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                        ('discount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                        ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                        ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                        ('date_created', models.DateTimeField(blank=True, null=True)),
                        ('last_updated', models.DateTimeField(blank=True, null=True)),
                        ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.client')),
                        ('converted_invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_devis', to='sales.invoice')),
                    ],
                    options={
                        'verbose_name_plural': 'Devis',
                        'ordering': ['-date_created'],
                    },
                ),
                migrations.AddField(
                    model_name='invoiceservice',
                    name='devis',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devis_services', to='sales.devis'),
                ),
            ],
            database_operations=[],
        ),
    ]
