# Generated by Django 6.0 on 2026-03-24 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0005_govinvoice_notes_govinvoice_submitted_at_and_more'),
        ('sales', '0023_devis_invoiceservice_shared'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_snapshot', models.CharField(max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('gov_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gov.govinvoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'gov_invoice')},
            },
        ),
    ]
