# Generated by Django 6.0 on 2026-04-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_notificationstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
