# Generated by Django 6.0 on 2026-05-22 17:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_creditnote_date_created_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceservice',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('1'), help_text='Quantity multiplier shown on the invoice line', max_digits=15),
        ),
    ]
