# Generated by Django 6.0 on 2026-05-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_invoiceservice_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='iban',
            field=models.CharField(blank=True, help_text='IBAN (International)', max_length=34, null=True),
        ),
    ]
