# Generated by Django 6.0 on 2026-07-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_settings_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='show_quantity',
            field=models.BooleanField(default=True, help_text='Display the Quantité column on the invoice detail and printed version'),
        ),
    ]
