# Generated by Django 6.0 on 2026-03-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_add_ngsign_client_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngsignclientaccount',
            name='signer_email',
            field=models.EmailField(blank=True, help_text='Email du compte NGSign autorisé à signer (ex: votre compte partner)', max_length=254),
        ),
    ]
