# Generated by Django 6.0 on 2026-05-18 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_ngsignclientaccount_signer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElfatooraClientAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, help_text='Identifiant elfatoora (en MAJUSCULES)', max_length=100)),
                ('password', models.CharField(blank=True, help_text='Mot de passe elfatoora', max_length=200)),
                ('mf', models.CharField(blank=True, help_text='Matricule fiscal du contribuable', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACTIVE', 'ACTIVE'), ('ERROR', 'ERROR')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='elfatoora_account', to='tenants.tenant')),
            ],
        ),
    ]
